name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION:     '22'
      BUILD_COMMAND:    ${{ secrets.BUILD_COMMAND  || 'npm run build' }}
      PUBLIC_DIR:       ${{ secrets.PUBLIC_DIR     || 'build' }}
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_TARGET:  ${{ secrets.FIREBASE_TARGET || '' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Verify Node version
        run: node --version
        # should print something like v22.x.x

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: ${{ env.BUILD_COMMAND }}

      - name: Deploy to Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId:              ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId:              live
          # If you have multiple hosting targets, uncomment the next line:
          # target:                ${{ secrets.FIREBASE_TARGET }}
