name: Build & Deploy to Firebase Hosting.

on:
  push:
    # adjust branches as needed
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # inject your vars here (FIREBASE_TOKEN must come from Secrets)
    env:
      NODE_VERSION: ${{ secrets.NODE_VERSION     || '16' }}
      BUILD_COMMAND: ${{ secrets.BUILD_COMMAND   || 'npm run build' }}
      PUBLIC_DIR: ${{ secrets.PUBLIC_DIR         || 'build' }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_TARGET: ${{ secrets.FIREBASE_TARGET || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build SPA
        run: ${{ env.BUILD_COMMAND }}

      - name: Deploy to Firebase Hosting
        # using community action; you can also install firebase-tools directly
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: >
            deploy
            --project ${{ env.FIREBASE_PROJECT_ID }}
            ${{ env.FIREBASE_TARGET && format('--only hosting:%s', env.FIREBASE_TARGET) }}
            --public ${{ env.PUBLIC_DIR }}
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
